bases:
  - values/helmfile-defaults.yaml


repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

---
releases:
  - name: decision-maker
    namespace: {{ .Environment.Values.namespace }}
    needs: [decision-maker-mongodb]
    chart: ../helm
    values:
      - values/service.yaml.gotmpl

  - name: decision-maker-mongodb
    namespace: {{ .Environment.Values.namespace }}
    chart: bitnami/mongodb
    version: 15.1.2
    values:
      - auth:
          rootPassword: root
          persistence:
            enabled: false
            storageClass: longhorn
            size: 1Gi

  - name: ingress-controller
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.9.0
    installed: true
    createNamespace: true
    values:
      - values/nginx.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    set:
      - name: installCRDs
        value: true