bases:
  - values/helmfile-defaults.yaml


repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

---
releases:
  - name: decision-maker
    namespace: {{ .Environment.Values.namespace }}
    chart: ../helm
    values:
      - values/service.yaml.gotmpl
  - name: decision-maker-mongodb
    namespace: {{ .Environment.Values.namespace }}
    chart: bitnami/mongodb
    version: 15.1.2
    values:
      - mongodbRootPassword:
          existingSecret: mongodb
          key: mongodb-root-password