apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-template.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart-template.name" . }}
    helm.sh/chart: {{ include "chart-template.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  SPRING_PROFILES_ACTIVE: {{ default "dev" .Values.decisionmaker.springProfile | quote }}
  dev-features.enabled: {{ .Values.decisionmaker.dev.enabled | quote }}
  SERVER_PORT: {{ .Values.decisionmaker.port | quote}}
  MONGODB_USERNAME: {{ .Values.decisionmaker.db.username | quote }}
  MONGODB_DATABASE: {{ .Values.decisionmaker.db.database | quote }}