{{- $fullName := include "chart-template.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-template.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chart-template.name" . }}
    helm.sh/chart: {{ include "chart-template.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart-template.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      labels:
        app.kubernetes.io/name: {{ include "chart-template.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }} # app.kubernetes.io/managed-by=Helm
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ $fullName }}
            - configMapRef:
                name: {{ $fullName }}
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: db_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: db_password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: db_name
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: userConnectionUri

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: github-registry