apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: public-dev
  name: dcm-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: survey.quantumlin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lite-bridge
                port:
                  number: 80
    - host: api.quantumlin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: decision-maker
                port:
                  number: 80
