apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcm-ingress
  namespace: public-dev
  annotations:
  cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: lite-bridge
                port:
                  number: 80
          - path: /api/decision-maker
            pathType: ImplementationSpecific
            backend:
              service:
                name: decision-maker
                port:
                  number:

  tls:
    - hosts:
      - survey.quantumlin.com
      secretName: letsencrypt-staging-survey-quantumlin