apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcm-ingress
  namespace: public-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - survey.quantumlin.com
      secretName: letsencrypt-prod-survey-quantumlin
    - hosts:
        - api.quantumlin.com
      secretName: letsencrypt-prod-api-quantumlin
  rules:
    - host: survey.quantumlin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lite-bridge
                port:
                  number: 80
    - host: api.quantumlin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: decision-maker
                port:
                  number: 80