apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcm-ingress
  namespace: public-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dcm/survey
            pathType: Prefix
            backend:
              service:
                name: lite-bridge
                port:
                  number: 80
          - path: /ttc/decision
            pathType: Prefix
            backend:
              service:
                name: decision-maker
                port:
                  number: 80