apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ include "chart-template.fullname" . }}-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: {{ .Values.mongodb.version | quote}}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ include "chart-template.fullname" . }}
      db: {{ include "chart-template.fullname" . }}
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ include "chart-template.fullname" . }}-mongodb-generated
        key: "userPassword"
      roles:
        - name: readWrite
          db: {{ include "chart-template.fullname" . }}
      scramCredentialsSecretName: {{ include "chart-template.fullname" . }}-mongodb-scram-user
    - name: {{ include "chart-template.fullname" . }}-admin
      db: admin
      passwordSecretRef: # a reference
      roles:
        - name: root
          db: admin
      scramCredentialsSecretName: {{ include "chart-template.fullname" . }}-mongodb-scram-admin
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongodb-container
              resources:
                requests:
                  memory: 1024Mi
                  cpu: 100m
                limits:
                  memory: 1024Mi
                  cpu: 2
          serviceAccountName: mongodb-database