{{- $fullName := include "chart-template.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: {{ .Values.decisionmaker.db.uri | quote }}
  MONGODB_PASSWORD: {{ .Values.decisionmaker.db.password | quote }}
---
{{- define "imagePullSecret" }}
{{- with .Values.containerRegistry }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: github-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

