{{- $fullName := include "chart-template.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: {{ .Values.decisionmaker.db.uri | quote }}
  MONGODB_PASSWORD: {{ .Values.decisionmaker.db.password | quote }}