---
helmDefaults:
  cleanupOnFail: false
  verify: false
  wait: true
  timeout: 900
  recreatePods: false
  force: false
  historyMax: 20
  createNamespace: false
  devel: true
  skipDeps: false

environments:
  "{{ .Environment.Name }}":
    values:
      - values/default-values.yaml
      - values/environments/public-dev.yaml