services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=thrive'
      - 'MONGO_INITDB_ROOT_PASSWORD=test'
      - 'MONGO_INITDB_ROOT_USERNAME=test'
    ports:
      - '27017'
