name: tech-thrive-catalyst

on:
  push:
    paths:
      - decision-maker/**
      - .github/workflows/decision-maker.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: beergode/shared-pipeline-templates/.github/workflows/.buildGradle.yml@main
    with:
      repository_name: ${{ github.repository }}

  semverDryRun:
    uses: beergode/shared-pipeline-templates/.github/workflows/.semver.yml@main
    with:
      repository_name: ${{ github.repository }}

  buildAndPublishImage:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: beergode/shared-pipeline-templates/.github/workflows/.buildAndPublishImage.yml@main
    with:
      image_name: ${{ github.repository }}/decision-maker
      tag: ${{ needs.semver.outputs.newTag }}
      repository_name: ${{ github.repository }}
    secrets:
      registry_username: ${{ github.repository_owner
      registry_password: ${{ secrets.GITHUB_TOKEN }}
    needs: [build, semverDryRun]

  publishTag:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: beergode/shared-pipeline-templates/.github/workflows/.semver.yml@main
    with:
      dry_run: false
      repository_name: ${{ github.repository }}
    needs: buildAndPublishImage

  deploymentTrigger:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: beergode/shared-pipeline-templates/.github/workflows/.deployDO.yml@main
    with:
      repository_name: ${{ github.repository }}
      repository_username: ${{ github.repository_owner }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
      DO_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      DO_CLUSTER_ID: ${{ secrets.DO_CLUSTER_ID }}
    needs: publishTag